server.port=8090
logging.level.com.cognizant.springlearn=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} : %msg%n
jwt.secret=Cognizant-Digital-Nurture-JWT-Secret-Key-Must-Be-Long